version: '3.4'

services:
    inverter:
        image: ${DOCKER_REGISTRY-}inverter
        build:
            context: .
            dockerfile: src/inverter/Dockerfile

        # Override entry point for debugging
        #entrypoint: ["/bin/bash"]

        privileged: true

        volumes:
           - ./src/inverter/mqtt.json:/app/mqtt.json

        devices:
          - /dev/ttyUSB0:/dev/ttyUSB0:rwm
    
    
